apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.0.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: 'Admin'
          volumeMounts:
            - name: grafana-datasources-volume
              mountPath: /etc/grafana/provisioning/datasources/
            - name: grafana-dashboard-providers-volume
              mountPath: /etc/grafana/provisioning/dashboards/
            - name: grafana-dashboards-volume
              mountPath: /var/lib/grafana/dashboards/
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-datasources-volume
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-providers-volume
          configMap:
            name: grafana-dashboard-providers
        - name: grafana-dashboards-volume
          configMap:
            name: grafana-dashboards
        - name: grafana-storage-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
