apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: egovernment
type: Opaque
stringData:
  AuthDb__Password: postgres_dev
  CitizenDb__Password: postgres_dev
  RequestDb__Password: postgres_dev
  DocumentDb__Password: postgres_dev
  NotificationDb__Password: postgres_dev
  AuditDb__Password: postgres_dev
  Jwt__Key: CHANGE_ME_GENERATE_A_RANDOM_SECRET_MINIMUM_32_CHARS
  Admin__Email: admin@egovernment.gov
  Admin__Password: Admin123!
  Admin__FullName: System Administrator
  RabbitMQ__Username: egov
  RabbitMQ__Password: egov-rabbitmq-dev-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: egovernment-db
type: Opaque
stringData:
  AuthDb__Password: postgres_dev
  CitizenDb__Password: postgres_dev
  RequestDb__Password: postgres_dev
  DocumentDb__Password: postgres_dev
  NotificationDb__Password: postgres_dev
  AuditDb__Password: postgres_dev